#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
CHAIN_NAME="${CHAIN_NAME:-tbthree}"
CHAIN_DIR="${CHAIN_DIR:-$ROOT_DIR/chain/$CHAIN_NAME}"
CHAIN_HOME="${CHAIN_HOME:-$CHAIN_DIR/.$CHAIN_NAME}"
CHAIN_ID="${CHAIN_ID:-$CHAIN_NAME}"
CHAIN_RPC="${CHAIN_RPC:-tcp://127.0.0.1:26657}"
BACKEND_ENV="$ROOT_DIR/backend/.env"

TB3D="${TB3D:-$CHAIN_DIR/build/${CHAIN_NAME}d}"

if [ ! -x "$TB3D" ]; then
  # fallback to PATH
  if command -v "${CHAIN_NAME}d" >/dev/null 2>&1; then
    TB3D="$(command -v "${CHAIN_NAME}d")"
  fi
fi

if [ ! -x "$TB3D" ]; then
  echo "❌ Cannot find chain binary ($TB3D). Make sure chain has been built (run: make up)." >&2
  exit 1
fi

if [ ! -d "$CHAIN_HOME" ]; then
  echo "❌ Chain home not found: $CHAIN_HOME" >&2
  echo "Start chain first: make up" >&2
  exit 1
fi

KEYRING="test"
DENOM="utoken"
FUND_AMOUNT="100000000$DENOM"

add_key() {
  local name="$1"
  if "$TB3D" keys show "$name" --keyring-backend "$KEYRING" --home "$CHAIN_HOME" >/dev/null 2>&1; then
    echo "✅ key exists: $name"
    return 0
  fi
  echo "🔑 creating key: $name"
  "$TB3D" keys add "$name" --keyring-backend "$KEYRING" --home "$CHAIN_HOME" --output json
}

get_addr() {
  local name="$1"
  "$TB3D" keys show "$name" -a --keyring-backend "$KEYRING" --home "$CHAIN_HOME"
}

# Create demo keys
ALICE_ADDR="$(get_addr alice)" || true
if [ -z "${ALICE_ADDR:-}" ]; then
  echo "⚠️ alice key not found in keyring. Ignite usually creates alice/bob."
fi

CLOUD_JSON="$(add_key cloud1 || true)"
VEH_JSON="$(add_key vehicle1 || true)"
E1_JSON="$(add_key edge1 || true)"
E2_JSON="$(add_key edge2 || true)"
E3_JSON="$(add_key edge3 || true)"

CLOUD_ADDR="$(get_addr cloud1)"
VEH_ADDR="$(get_addr vehicle1)"
E1_ADDR="$(get_addr edge1)"
E2_ADDR="$(get_addr edge2)"
E3_ADDR="$(get_addr edge3)"
ALICE_ADDR="$(get_addr alice)"

# Fund accounts from alice
fund() {
  local to="$1"
  echo "💸 funding $to with $FUND_AMOUNT"
  "$TB3D" tx bank send alice "$to" "$FUND_AMOUNT" \
    --chain-id "$CHAIN_ID" --node "$CHAIN_RPC" --home "$CHAIN_HOME" \
    --keyring-backend "$KEYRING" -y --broadcast-mode block >/dev/null
}

fund "$CLOUD_ADDR" || true
fund "$VEH_ADDR" || true
fund "$E1_ADDR" || true
fund "$E2_ADDR" || true
fund "$E3_ADDR" || true

cat > "$BACKEND_ENV" <<ENV
# Auto-generated by scripts/init_demo_accounts.sh
CHAIN_NAME=$CHAIN_NAME
CHAIN_ID=$CHAIN_ID
CHAIN_RPC=$CHAIN_RPC
CHAIN_HOME=$CHAIN_HOME
TB3D=$TB3D
KEYRING_BACKEND=$KEYRING
DENOM=$DENOM

ADMIN_NAME=alice
ADMIN_ADDR=$ALICE_ADDR
CLOUD_NAME=cloud1
CLOUD_ADDR=$CLOUD_ADDR
VEHICLE1_NAME=vehicle1
VEHICLE1_ADDR=$VEH_ADDR
EDGE1_NAME=edge1
EDGE1_ADDR=$E1_ADDR
EDGE2_NAME=edge2
EDGE2_ADDR=$E2_ADDR
EDGE3_NAME=edge3
EDGE3_ADDR=$E3_ADDR
ENV

echo "✅ Demo accounts initialized. Backend .env written: $BACKEND_ENV"
